var data = [
    {
        _id="1",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="2",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="3",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="4",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="5",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="6",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="7",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="8",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },
    {
        _id="8",
        title: "Boogie Board",
        description:"This is a boogie board",
        image: "boogie-board.jpg",
        price: 199.99,
        category: "Boogie Boards",
        discount: 5,
    },

    
];
